
const Images = {
    logo: require('../assets/images/logo.png'),
    onBoardFirst : require('../assets/images/onboard/first.png'),
    onBoardSecond : require('../assets/images/onboard/second.png'),
    onBoardThird : require('../assets/images/onboard/third.png'),
    onBoardFourth : require('../assets/images/onboard/fourth.png'),
    onBoardBottom : require('../assets/images/onboard/bottom.png'),
    descriptionLogo : require('../assets/images/description-logo.png'),
    successLogo : require('../assets/images/success-logo.png'),
    postBlackTab : require('../assets/images/tabsIcons/black/post-black-tab.png'),
    tipsBlackTab : require('../assets/images/tabsIcons/black/tips-black-tab.png'),
    itemsBlackTab : require('../assets/images/tabsIcons/black/items-black-tab.png'),
    rewardsBlackTab : require('../assets/images/tabsIcons/black/rewards-black-tab.png'),
    adsBlackTab : require('../assets/images/tabsIcons/black/ads-black-tab.png'),
    postGreenTab : require('../assets/images/tabsIcons/green/post-green-tab.png'),
    tipsGreenTab : require('../assets/images/tabsIcons/green/tips-green-tab.png'),
    itemsGreenTab : require('../assets/images/tabsIcons/green/items-green-tab.png'),
    rewardsGreenTab : require('../assets/images/tabsIcons/green/rewards-green-tab.png'),
    adsGreenTab : require('../assets/images/tabsIcons/green/ads-green-tab.png'),
    homeLogo : require('../assets/images/home/home-logo.png'),
    homeBackground : require('../assets/images/home/home-background.png'),
    homeCategoryBooks : require('../assets/images/home/home-category-books.png'),
    homeCategoryElectronics : require('../assets/images/home/home-category-electronics.png'),
    homeCategoryFurniture : require('../assets/images/home/home-category-furniture.png'),
    homeCategoryMobile : require('../assets/images/home/home-category-mobile.png'),
    homeCategoryShoes : require('../assets/images/home/home-category-shoes.png'),
    homeFilter : require('../assets/images/home/home-filter.png'),
    homeSearch : require('../assets/images/home/home-search.png'),
    homeLocation : require('../assets/images/home/home-location.png'),
    homeBitLogo : require('../assets/images/home/home-bitLogo.png'),
    homeMerchantShowcasetion : require('../assets/images/home/home-merchantShowcase.png'),
    homePopularListing : require('../assets/images/home/home-popularListing.png'),
    homePostVector : require('../assets/images/home/home-postVector.png'),
    homeBellIcon : require('../assets/images/home/home-bellIcon.png'),
    homeGreenBit : require('../assets/images/home/home-greenBit.png'),
    homeProfile : require('../assets/images/home/home-profile.png'),
    homeMessageIcon : require('../assets/images/home/home-messageIcon.png'),
    homeDollarLogo : require('../assets/images/home/home-dollarLogo.png'),
    homeTools : require('../assets/images/home/home-tools.png'),
    homeLuxury : require('../assets/images/home/home-luxury.png'),
    homeServices : require('../assets/images/home/home-services.png'),
    homeVehicles : require('../assets/images/home/home-vehicles.png'),
    homeProperty : require('../assets/images/home/home-property.png'),
    homeBaby : require('../assets/images/home/home-baby.png'),
    homeToys : require('../assets/images/home/home-toys.png'),
    homePets : require('../assets/images/home/home-pets.png'),
    homeFoodDrinks : require('../assets/images/home/home-food&drinks.png'),
    homeSports : require('../assets/images/home/home-sports.png'),
    homeStationary : require('../assets/images/home/home-stationary.png'),
    homeMusic : require('../assets/images/home/home-music.png'),
    homeArt : require('../assets/images/home/home-art.png'),
    homeOthers : require('../assets/images/home/home-others.png'),
    backArrowIcon : require('../assets/images/back-arrowIcon.png'),
    uploadImageIcon : require('../assets/images/postTab/upload-image.png'),
    dropDownIcon : require('../assets/images/postTab/dropDownIcon.png'),


}



export default Images;